layout_spectrum: 1
typography_spectrum: 0.8397601
color:
  saturation: 0.698711
  brandStrength: 0.480666
  lightness: 0.5494092
  brandColors:
    - '#000000'
    - '#ED1C24'
    - '#C4171E'
    - '#220405'
    - '#770E12'
  rhythmicContrast: 0.7223416
name: KJC photography
